<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <AssemblyVersion>2025.8.22.577</AssemblyVersion>
    <FileVersion>2025.8.22.577</FileVersion>
	<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
	<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
	<BaseOutputPath>..\..\Release\Eto.Forms\</BaseOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="bin\**" />
    <EmbeddedResource Remove="bin\**" />
    <None Remove="bin\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Eto.Forms" Version="2.9.0" />
    <PackageReference Include="Eto.Serialization.Json" Version="2.9.0" />
    <PackageReference Include="System.Management" Version="9.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\x8086NetEmu\x8086NetEmu.vbproj" />
  </ItemGroup>

</Project>