<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyVersion>2026.3.31.612</AssemblyVersion>
    <FileVersion>2026.3.31.612</FileVersion>
	<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
	<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
	<BaseOutputPath>..\..\Release\Eto.Forms\</BaseOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="bin\**" />
    <EmbeddedResource Remove="bin\**" />
    <None Remove="bin\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Eto.Forms" Version="2.11.0" />
    <PackageReference Include="Eto.Serialization.Json" Version="2.11.0" />
    <PackageReference Include="System.Management" Version="10.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\x8086NetEmu\x8086NetEmu.vbproj" />
  </ItemGroup>

</Project>