<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <!-- Core Properties -->
    <OutputType>Exe</OutputType>
    <TargetFramework>net481</TargetFramework>
    <RootNamespace>RunTests2</RootNamespace>
    <AssemblyName>RunTests2</AssemblyName>

    <!-- Platform Configuration -->
    <Platforms>AnyCPU;x86;x64</Platforms>

    <!-- Custom Build Settings -->
    <OutputPath>..\Release\</OutputPath>
    <Prefer32Bit>false</Prefer32Bit>
    <Deterministic>true</Deterministic>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>

    <!-- Third-Party Tooling Properties -->
    <ShouldCreateLogs>False</ShouldCreateLogs>
    <AdvancedSettingsExpanded>True</AdvancedSettingsExpanded>
    <UpdateAssemblyVersion>False</UpdateAssemblyVersion>
    <UpdateAssemblyFileVersion>False</UpdateAssemblyFileVersion>
    <UpdateAssemblyInfoVersion>False</UpdateAssemblyInfoVersion>
    <UpdatePackageVersion>False</UpdatePackageVersion>
    <AssemblyInfoVersionType>SettingsVersion</AssemblyInfoVersionType>
    <InheritWinAppVersionFrom>None</InheritWinAppVersionFrom>
  </PropertyGroup>

  <!-- Platform-Specific Settings -->
  <PropertyGroup Condition="'$(Platform)' == 'x86' Or '$(Platform)' == 'x64'">
    <LangVersion>7.3</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\x8086NetEmu\x8086NetEmu.vbproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>
</Project>