<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net9.0-windows7.0</TargetFramework>
		<AssemblyVersion>2025.8.22.233</AssemblyVersion>
		<FileVersion>2025.8.22.233</FileVersion>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
		<BaseOutputPath>..\..\Release\Eto.Forms\</BaseOutputPath>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\x8086NetEmuEto\x8086NetEmuEto.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Eto.Platform.Wpf" Version="2.9.0" />
	</ItemGroup>

</Project>
