<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<AssemblyVersion>2026.3.29.563</AssemblyVersion>
		<FileVersion>2026.3.29.563</FileVersion>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
		<BaseOutputPath>..\..\Release\Eto.Forms\</BaseOutputPath>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\x8086NetEmuEto\x8086NetEmuEto.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Eto.Platform.Gtk" Version="2.11.0" />
	</ItemGroup>

</Project>
