<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>Exe</OutputType>
    <StartupObject>x8086NetEmuConsole.MainModule</StartupObject>
    <SccProjectName></SccProjectName>
    <SccLocalPath></SccLocalPath>
    <SccAuxPath></SccAuxPath>
    <SccProvider></SccProvider>
    <ApplicationVersion>2018.3.2.366</ApplicationVersion>
    <ShouldCreateLogs>False</ShouldCreateLogs>
    <AdvancedSettingsExpanded>True</AdvancedSettingsExpanded>
    <UpdateAssemblyVersion>False</UpdateAssemblyVersion>
    <UpdateAssemblyFileVersion>False</UpdateAssemblyFileVersion>
    <UpdateAssemblyInfoVersion>False</UpdateAssemblyInfoVersion>
    <UpdatePackageVersion>False</UpdatePackageVersion>
    <AssemblyInfoVersionType>SettingsVersion</AssemblyInfoVersionType>
    <InheritWinAppVersionFrom>None</InheritWinAppVersionFrom>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <OptionExplicit>On</OptionExplicit>
    <OptionCompare>Binary</OptionCompare>
    <OptionStrict>Off</OptionStrict>
    <OptionInfer>On</OptionInfer>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|AnyCPU'">
    <OutputPath>..\Release\</OutputPath>
    <DefineConstants>Win32 = True</DefineConstants>
    <DocumentationFile>x8086NetEmuConsole.xml</DocumentationFile>
    <NoWarn>42016,41999,42017,42018,42019,42032,42036,42020,42021,42022</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|AnyCPU'">
    <OutputPath>..\Release\</OutputPath>
    <DefineConstants></DefineConstants>
    <DocumentationFile>x8086NetEmuConsole.xml</DocumentationFile>
    <NoWarn>42016,41999,42017,42018,42019,42032,42036,42020,42021,42022</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Update="My Project\Resources.Designer.vb">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="My Project\Application.Designer.vb" />
    <Compile Remove="My Project\Settings.Designer.vb" />
    <None Remove="My Project\Application.myapp" />
    <None Remove="My Project\Settings.settings" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\x8086NetEmuRenderers\x8086NetEmuRenderers.vbproj" />
    <ProjectReference Include="..\x8086NetEmu\x8086NetEmu.vbproj" />
  </ItemGroup>
  <ProjectExtensions>
    <VisualStudio>
      <UserProperties BuildVersion_DetectChanges="False" BuildVersion_BuildAction="Both" BuildVersion_UpdateFileVersion="True" BuildVersion_UpdateAssemblyVersion="True" BuildVersion_BuildVersioningStyle="None.None.Increment.None" />
    </VisualStudio>
  </ProjectExtensions>
</Project>