.TH IHEX 1 "2004-06-10" "HH" "misc-utils"

.SH NAME
ihex \- Convert Intel hex files to and from binary

.SH SYNOPSIS
.BI ihex " -e [options] [input...]"

.BI ihex " -d [options] [input [output]]"

.BI ihex " --help"

.BI ihex " --version"

.SH DESCRIPTION
.BR ihex (1)
converts binary files to intel hex files and vice versa.

.SH OPTIONS

.TP
.B -e, --encode
Convert a binary stream to a hex file. This is the default if neither
.B -e
nor
.B -d
is specified.
\
.TP
.B -d, --decode
Convert a hex file to a binary stream.
\
.TP
.BI "-i " string
Set the input file name. Default is stdin. When encoding, this
option can be used multiple times to combine several binary
files into one hex file.
\
.TP
.BI "-o " string
Set the output file name. Default is stdout. When decoding each
occurance of '#' will be replaced by a hex digit of the base
address of the chunk contained in that file. When encoding, this
option must preceede the first
.B -i
option on the command line.
\
.TP
.BI "-c " string
Set an input file for encoding and assume that the file is
an intel hex file. This does a simple pass through conversion
(file consistency is not checked but checksums are recalculated).
This option is invalid when decoding. For encoding it can be
used mutliple times to merge multiple intel hex files into one.
\
.TP
.BI "-a, --address " int
Set the base address for the next input file when encoding.
\
.TP
.BI "-n, --record-size " int
Set the maximum record size for encoding.
\
.TP
.B --help
Print usage information
\
.TP
.B --version
Print version information

.SH SEE ALSO
.BR hex (1)

.SH AUTHOR
Hampa Hug <hampa@hampa.ch>
